project:
  type: website

website:
  title: "qblog"
  navbar:
    right:
      - about.qmd
      - tags.qmd
      - icon: github
        href: https://github.com/pmean
format:
  html:
    theme: cosmo
    css: styles.css



